# Generated by Django 5.0.6 on 2024-07-01 02:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('telephone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=170, unique=True)),
                ('contenu', models.CharField(default='tres interessant votre travaile Cybercoprs.cm continuer dans la meme lance', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poster', models.CharField(default='CyberCorpscm', max_length=64)),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(max_length=255)),
                ('date_post', models.DateField(auto_now_add=True)),
                ('contenu_post', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_post', models.ImageField(upload_to='static/img/posts')),
            ],
        ),
    ]
