# Generated by Django 5.0.6 on 2024-07-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cybercorpscm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='telephone',
            field=models.IntegerField(default='656565656', unique=True),
        ),
    ]
