# Generated by Django 5.0.6 on 2024-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cybercorpscm', '0002_alter_message_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(upload_to='img/posts'),
        ),
    ]
